-- Criação da tabela de Produtos
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric not null,
  category text,
  image_url text, -- URL da imagem no Storage
  stock integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Criação da tabela de Banners/Slides
create table public.banners (
  id bigint generated by default as identity primary key,
  title text,
  image_url text not null,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar Row Level Security (Segurança)
alter table public.products enable row level security;
alter table public.banners enable row level security;

-- Políticas de Acesso (Simples para começar)
-- Leitura pública (qualquer um pode ver produtos)
create policy "Produtos são visíveis para todos" on public.products for select using (true);
create policy "Banners são visíveis para todos" on public.banners for select using (true);

-- Escrita apenas para autenticados (Admin) - Na prática precisa de auth configurado, mas com a chave Anon o insert falha por padrão se não tiver policy
-- Para simplificar o desenvolvimento inicial (CUIDADO: isso permite criaçao se tiver a chave anon, ideal é usar auth.uid())
create policy "Permitir insert para todos (DEV)" on public.products for insert with check (true);
create policy "Permitir update para todos (DEV)" on public.products for update using (true);
create policy "Permitir delete para todos (DEV)" on public.products for delete using (true);

-- Configuração do Storage (Baldes de imagens)
insert into storage.buckets (id, name, public) values ('products', 'products', true);
insert into storage.buckets (id, name, public) values ('banners', 'banners', true);

-- Políticas do Storage
create policy "Imagens públicas" on storage.objects for select using ( bucket_id in ('products', 'banners') );
create policy "Upload irrestrito (DEV)" on storage.objects for insert with check ( bucket_id in ('products', 'banners') );
