-- Remove a tabela anterior se existir (para corrigir o erro de criação)
DROP TABLE IF EXISTS site_settings;

-- Recria a tabela com ID permitindo inserção manual (BY DEFAULT)
CREATE TABLE site_settings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    site_title TEXT DEFAULT 'La Vibe Fit - Moda Fitness',
    site_description TEXT DEFAULT 'Moda fitness feminina em Manaus. Leggings, tops, shorts e conjuntos com estilo e conforto.',
    keywords TEXT DEFAULT 'moda fitness, manaus, roupa de academia, legging, top, la vibe fit',
    google_verification_code TEXT,
    
    -- Dados para SEO Local (Schema.org)
    business_name TEXT DEFAULT 'La Vibe Fit',
    city TEXT DEFAULT 'Manaus',
    state TEXT DEFAULT 'AM',
    address TEXT,
    phone TEXT DEFAULT '5592984665689',
    
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Inserir configuração inicial
INSERT INTO site_settings (id, site_title)
VALUES (1, 'La Vibe Fit - Moda Fitness');

-- Políticas de Segurança
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;

-- Permitir leitura para todos (essencial para o site funcionar)
CREATE POLICY "Settings are viewable by everyone" ON site_settings
FOR SELECT USING (true);

-- Permitir edição (controle feito pelo painel Admin)
CREATE POLICY "Settings are updatable by public" ON site_settings
FOR UPDATE USING (true);

-- Permitir inserção (caso precise)
CREATE POLICY "Settings are insertable by public" ON site_settings
FOR INSERT WITH CHECK (true);
